### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gao117348222** [egbertbouman/APKfetch#1]
can this run on windows,and can  This download Increase google play console number?

**Comment by egbertbouman** [comment]
Yes, it runs on Windows. I'm not sure what you mean with your second question. APKfetch downloads APKs from the Google Play store using an existing Google account. It will work for all APKs that are compatible with the device APKfetch simulates.

**Comment by gao117348222** [comment]
in apkfetch.py,version(self, package_name) response 200 but response.content is empty,so Could not get version-code,do you have same problem?

**Comment by egbertbouman** [comment]
It could be that the device that APKfetch simulates is not compatible with the app you're trying to download. Can you give me the name of the app, so I can test it?

**Comment by gao117348222** [comment]
Actually,I test many apps,All cant get Version,One of them is the one I write,packetname is com.ugamehome.casual.SurroundCrazyAlpaca .
I test step by step,I can login ,get auth,but next step get version is empty .
here is my command 
python apkfetch.py --user myemail --passwd mypsw --androidid  myandroid --package  com.ugamehome.casual.SurroundCrazyAlpaca

**Comment by egbertbouman** [comment]
I just did some testing on multiple Windows machines, but for me everything
seems to work OK for the package you mentioned. Did you try without the
--androidid option?

**Comment by gao117348222** [comment]
god,when i remove --androidid option.Its ok,so what is my problem?if without androidid,the apkfetch will genertation it random?

**Comment by egbertbouman** [comment]
It looks like the device associated with your androidid is not compatible with the APK.

Without the `--androidid` option, APKfetch will just get you a new one. Once you have your new androidid, next time you can use `--androidid` with your new id.

**Comment by gao117348222** [comment]
thank you ,you help me solve my big problem.
