### ISSUE TITLE
Error: Can't install. Please try again later.

### ISSUE THREAD

**Issue by LeetCodes** [egbertbouman/APKfetch#3]
hi, i keep getting this error

[ec2-user APKfetch]$ python apkfetch.py --user leet@gmail.com --passwd password1 --androidid 3B00227471A46EEA --package polis.app.callrecorder.pro
Error: Can't install. Please try again later.

**Comment by egbertbouman** [comment]
@LeetCodes APKfetch does not support downloading paid apps. Is does work with the free version of the app (polis.app.callrecorder).

**Comment by LeetCodes** [comment]
[ec2-user@ip-172-31-14-29 APKfetch]$ python apkfetch.py --user d4rk@leetcodes.com --passwd password1 --androidid 3B00227471A46EEA --package com.facebook.mlite
Error: Google Play purchases are not supported in your country. Unfortunately you will not be able to complete purchases.


now it says this, any ideas what i should do? im in US, and this is a free app from facebook
