### ISSUE TITLE
Malware URL listed as constant

### ISSUE THREAD

**Issue by diogosimao** [egbertbouman/APKfetch#4]
Looks like a [malicious resource](https://android.clients.google.com/fdfe/details) is listed as a constant `GOOGLE_DETAILS_URL` as shown in the following [SecureList post](https://securelist.com/how-trojans-manipulate-google-play/75894/)

**Comment by egbertbouman** [comment]
The GOOGLE_DETAILS_URL url (https://android.clients.google.com/fdfe/details) is listed in the article while explaining how a malicious app could download an app from the playstore. This does not mean that the url itself is malicious.
